name: Test on PR Opened

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test

      - name: Leave review on failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const body = 'The test failed. Please check the code.';
            const { owner, repo, number } = context.issue;
            github.pulls.createReview({
              owner,
              repo,
              pull_number: number,
              body,
              event: 'REQUEST_CHANGES'
            });
